# Generated by Django 6.0.6 on 2026-06-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True, verbose_name='No. Invoice')),
                ('status', models.CharField(choices=[('unpaid', 'Aya Tagihan'), ('paid', 'Geus Dibayar'), ('partial', 'Bagean Dibayar'), ('cancelled', 'Dibatalkun')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Tunai'), ('bank_transfer', 'Transfer Bank'), ('insurance', 'Asuransi'), ('ewallet', 'E-Wallet')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal (Rp)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diskon (Rp)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pajak (Rp)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (Rp)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jumlah Dibayar (Rp)')),
                ('notes', models.TextField(blank=True, verbose_name='Catetan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='appointments.appointment', verbose_name='Appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient', verbose_name='Pasien')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice-invoice',
                'db_table': 'billing_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Katerangan')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Satuan (Rp)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (Rp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Item Invoice',
                'verbose_name_plural': 'Item-Item Invoice',
                'db_table': 'billing_invoice_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Tunai'), ('bank_transfer', 'Transfer Bank'), ('insurance', 'Asuransi'), ('ewallet', 'E-Wallet')], max_length=20, verbose_name='Metode Pembayaran')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah (Rp)')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='No. Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catetan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran-pembayaran',
                'db_table': 'billing_payment',
                'ordering': ['-payment_date'],
            },
        ),
    ]
