# Generated by Django 6.0.6 on 2026-06-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date_start', models.DateField(verbose_name='Tanggal Mimiti')),
                ('report_date_end', models.DateField(verbose_name='Tanggal Akhir')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='Total Kunjungan')),
                ('completed_visits', models.PositiveIntegerField(default=0, verbose_name='Kunjungan Réngsé')),
                ('cancelled_visits', models.PositiveIntegerField(default=0, verbose_name='Kunjungan Dibatalkun')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Pendapatan (Rp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laporan Kunjungan',
                'verbose_name_plural': 'Laporan-laporan Kunjungan',
                'db_table': 'reports_visit_report',
                'ordering': ['-report_date_end'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.DateField(verbose_name='Bulan Laporan')),
                ('total_appointments', models.PositiveIntegerField(default=0, verbose_name='Total Appointment')),
                ('completed_appointments', models.PositiveIntegerField(default=0, verbose_name='Appointment Réngsé')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Pendapatan (Rp)')),
                ('patient_satisfaction', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Kepuasan Pasien (1-5)')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='doctors.doctor', verbose_name='Dokter')),
            ],
            options={
                'verbose_name': 'Kinerja Dokter',
                'verbose_name_plural': 'Kinerja-kinerja Dokter',
                'db_table': 'reports_doctor_performance',
                'ordering': ['-report_month'],
                'unique_together': {('doctor', 'report_month')},
            },
        ),
    ]
