# Generated by Django 6.0.6 on 2026-06-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ngaran Obat')),
                ('generic_name', models.CharField(blank=True, max_length=200, verbose_name='Ngaran Generik')),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('kaplet', 'Kaplet'), ('sirup', 'Sirup'), ('krim', 'Krim/Salep'), ('injeksi', 'Injeksi'), ('kapsul', 'Kapsul'), ('tetes', 'Tetes')], max_length=20, verbose_name='Bentuk')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Produsen')),
                ('unit', models.CharField(default='tablet', max_length=20, verbose_name='Satuan')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Harga (Rp)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Batas Kadaluarsa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obat',
                'verbose_name_plural': 'Obat-obatan',
                'db_table': 'prescriptions_medicine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Diagnosa')),
                ('treatment_notes', models.TextField(blank=True, verbose_name='Catetan Pangobatan')),
                ('status', models.CharField(choices=[('written', 'Ditulisan'), ('paid', 'Dibayar'), ('dispensed', 'Diresepkeun'), ('cancelled', 'Dibatalkun')], default='written', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment', verbose_name='Appointment')),
            ],
            options={
                'verbose_name': 'Resep',
                'verbose_name_plural': 'Resep-resep',
                'db_table': 'prescriptions_prescription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frequency', models.CharField(max_length=100, verbose_name='Kadaliwuran')),
                ('duration', models.CharField(max_length=100, verbose_name='Durasian')),
                ('instructions', models.TextField(blank=True, verbose_name='Petunjuk')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='prescriptions.medicine', verbose_name='Obat')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription', verbose_name='Resep')),
            ],
            options={
                'verbose_name': 'Item Resep',
                'verbose_name_plural': 'Item-Item Resep',
                'db_table': 'prescriptions_prescription_item',
                'ordering': ['id'],
            },
        ),
    ]
