# Generated by Django 6.0.6 on 2026-06-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Tanggal Appointment')),
                ('appointment_time', models.TimeField(verbose_name='Waktu Appointment')),
                ('status', models.CharField(choices=[('scheduled', 'Dijadwalkeun'), ('in_progress', 'Dibérékeun'), ('completed', 'Réngsé'), ('cancelled', 'Dibatalkun'), ('no_show', 'Henteu Teu (No Show)')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Darurat')], default='normal', max_length=20)),
                ('reason', models.TextField(verbose_name='Alasan Kunjungan')),
                ('notes', models.TextField(blank=True, verbose_name='Catetan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor', verbose_name='Dokter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Pasien')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointment-appointment',
                'db_table': 'appointments_appointment',
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4d4b79_idx'), models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_8037cd_idx')],
            },
        ),
    ]
