# Generated by Django 6.0.6 on 2026-06-20 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='NIK')),
                ('date_of_birth', models.DateField(verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Pawéwé')], max_length=1, verbose_name='Jenis Kalamin')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3, verbose_name='Golongan Darah')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Kontak Darurat')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='No. Kontak Darurat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Pasien',
                'verbose_name_plural': 'Pasien-pasien',
                'db_table': 'patients_patient',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
