# Generated by Django 6.0.6 on 2026-06-20 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='No. STR')),
                ('specialization', models.CharField(choices=[('umum', 'Dokter Umum'), ('gigi', 'Dokter Gigi'), ('kulit', 'Dokter Kulit & Kelamin'), ('anak', 'Dokter Anak'), ('jantung', 'Dokter Jantung'), ('tnt', 'Dokter THT'), ('mata', 'Dokter Mata'), ('kandungan', 'Dokter Kandungan'), ('bedah', 'Dokter Bedah')], default='umum', max_length=20, verbose_name='Spesialisasi')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Pendidikan Terakhir')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Taun Pangalaman')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Biaya Konsultasi (Rp)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Sadayang Tersedia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Dokter',
                'verbose_name_plural': 'Dokter-dokter',
                'db_table': 'doctors_doctor',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
